services:
  postgres:
    build:
      context: .
      dockerfile: pgvector.Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d ai_model_test"]
      interval: 10s
      start_period: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - cdp-tenant

  migrator:
    build:
      context: ./migrator
    image: migrator
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cdp-tenant
    env_file:
      - .env
    volumes:
      - ./changelog:/liquibase/services/ai_model_test/changelog

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  service:
    build:
      context: .
      target: development
    ports:
      - 8085:8085
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      PORT: 8085
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      POSTGRES_DB: "ai_model_test"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /home/python/app/app
          ignore:
            - README.md
            - "**/*.md"
            - "**/test_*.py"
            - tests/**/*
            - .git/**/*
            - .venv/**/*
            - .pytest_cache/**/*
            - .ruff_cache/**/*
            - .vscode/**/*
            - .github/**/*
            - requirements-dev.txt
            - pytest.ini
            - .pre-commit-config.yaml
            - sonar-project.properties
            - LICENCE
        - action: rebuild
          path: ./pyproject.toml
    networks:
      - cdp-tenant

volumes:
  mongodb-data:
  postgres-data:

networks:
  cdp-tenant:
    driver: bridge
